### ISSUE TITLE
在VOC数据集上训练遇见报错

### ISSUE THREAD

**Issue by FelixCaae** [shaoshengsong/MobileNetV3-SSD#19]
raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/yww/MobileNetV3-SSD/vision/datasets/voc_dataset.py", line 65, in __getitem__
    image, boxes, labels = self.transform(image, boxes, labels)
  File "/home/yww/MobileNetV3-SSD/vision/ssd/data_preprocessing.py", line 34, in __call__
    return self.augment(img, boxes, labels)
  File "/home/yww/MobileNetV3-SSD/vision/transforms/transforms.py", line 55, in __call__
    img, boxes, labels = t(img, boxes, labels)
  File "/home/yww/MobileNetV3-SSD/vision/transforms/transforms.py", line 278, in __call__
    if overlap.min() < min_iou and max_iou < overlap.max():
  File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

怀疑是数据集的处理过程中出现0-size 的batch

**Comment by weidongmei123** [comment]
请问这部分您已经复现了吗？我也想用voc数据集训练，可是不知道怎么改配置代码

**Comment by shaoshengsong** [comment]
这里有个现成的使用VOC的,https://github.com/shaoshengsong/MobileNetV3-SSD-Compact-Version

**Comment by shaoshengsong** [comment]
> 请问这部分您已经复现了吗？我也想用voc数据集训练，可是不知道怎么改配置代码

这里有个现成的使用VOC的,https://github.com/shaoshengsong/MobileNetV3-SSD-Compact-Version

**Comment by weidongmei123** [comment]
非常感谢作者！我看到您新发的代码啦，请问这个代码也是ubuntu系统的吗？或者说windows系统上可以兼容吗？您前面那个代码我这边运行报错EOFError：Ran out of input
和在您的GitHub上提问的人遇到的报错一样，请问这种报错原因是什么呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: shaoshengsong <notifications@github.com&gt;
发送时间: 2020年4月22日 11:12
收件人: shaoshengsong/MobileNetV3-SSD <MobileNetV3-SSD@noreply.github.com&gt;
抄送: weidongmei123 <303462500@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[shaoshengsong/MobileNetV3-SSD] 在VOC数据集上训练遇见报错 (#19)





  
请问这部分您已经复现了吗？我也想用voc数据集训练，可是不知道怎么改配置代码
  
这里有个现成的使用VOC的,https://github.com/shaoshengsong/MobileNetV3-SSD-Compact-Version

**Comment by gongbutangjuan** [comment]
可用以下代码检查数据集是否有label或者类别缺失的情况
import argparse
import sys
import cv2
import os

import os.path  as osp
import numpy   as np

if sys.version_info[0] == 2:
    import xml.etree.cElementTree as ET
else:
    import xml.etree.ElementTree  as ET


parser    = argparse.ArgumentParser(
            description='Single Shot MultiBox Detector Training With Pytorch')
train_set = parser.add_mutually_exclusive_group()

parser.add_argument('--root', help='Dataset root directory path')

args = parser.parse_args()

CLASSES = (  # always index 
    'aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 
    'bus', 'car', 'cat', 'chair', 'cow', 'diningtable',
    'dog', 'horse', 'motorbike', 'pottedplant','sheep', 
    'sofa', 'train', 'tvmonitor', 'person')

annopath = osp.join('%s', 'Annotations', '%s.{}'.format("xml"))
imgpath  = osp.join('%s', 'JPEGImages',  '%s.{}'.format("png"))

def vocChecker(image_id, width, height, keep_difficult = False):
    target   = ET.parse(annopath % image_id).getroot()
    res      = []

    for obj in target.iter('object'):

        difficult = int(obj.find('difficult').text) == 1

        if not keep_difficult and difficult:
            continue

        name = obj.find('name').text.lower().strip()
        bbox = obj.find('bndbox')

        pts    = ['xmin', 'ymin', 'xmax', 'ymax']
        bndbox = []

        for i, pt in enumerate(pts):

            cur_pt = int(bbox.find(pt).text) - 1
            # scale height or width
            cur_pt = float(cur_pt) / width if i % 2 == 0 else float(cur_pt) / height

            bndbox.append(cur_pt)

        # print(name)
        label_idx =  dict(zip(CLASSES, range(len(CLASSES))))[name]
        bndbox.append(label_idx)
        res += [bndbox]  # [xmin, ymin, xmax, ymax, label_ind]
        # img_id = target.find('filename').text[:-4]
    # print(res)
    try :
        # print(np.array(res)[:,4])
        res_array = np.array(res)[:,:4]
        # print(np.array(res)[:,:4])
    except IndexError:
        # print("\nINDEX ERROR HERE !\n")
        print(image_id)
        # exit(0)
    return res  # [[xmin, ymin, xmax, ymax, label_ind], ... ]

if __name__ == '__main__' :

    i = 0

    for name in sorted(os.listdir(osp.join(args.root,'Annotations'))):
    # as we have only one annotations file per image
        i += 1
        # print(i)

        img    = cv2.imread(imgpath  % (args.root,name.split('.')[0]))
        height, width, channels = img.shape
        # print("path : {}".format(annopath % (args.root,name.split('.')[0])))
        res = vocChecker((args.root, name.split('.')[0]), height, width)
    print("Total of annotations : {}".format(i))

**Comment by shaoshengsong** [comment]
MobileNetV3-SSD-Compact-Version/create_data_lists.py ，打开 ，换成您自己的数据集路径

**Comment by shaoshengsong** [comment]
Ubuntu18.04测过，windows没测

**Comment by tianyuluan** [comment]
> ```
> raise self.exc_type(msg)
> ```
> 
> ValueError: Caught ValueError in DataLoader worker process 7.
> Original Traceback (most recent call last):
> File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 207, in **getitem**
> return self.datasets[dataset_idx][sample_idx]
> File "/home/yww/MobileNetV3-SSD/vision/datasets/voc_dataset.py", line 65, in **getitem**
> image, boxes, labels = self.transform(image, boxes, labels)
> File "/home/yww/MobileNetV3-SSD/vision/ssd/data_preprocessing.py", line 34, in **call**
> return self.augment(img, boxes, labels)
> File "/home/yww/MobileNetV3-SSD/vision/transforms/transforms.py", line 55, in **call**
> img, boxes, labels = t(img, boxes, labels)
> File "/home/yww/MobileNetV3-SSD/vision/transforms/transforms.py", line 278, in **call**
> if overlap.min() < min_iou and max_iou < overlap.max():
> File "/home/yww/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
> return umr_minimum(a, axis, None, out, keepdims)
> ValueError: zero-size array to reduction operation minimum which has no identity
> 
> 怀疑是数据集的处理过程中出现0-size 的batch

我也遇到了同样的问题，请问您解决了吗
