### ISSUE TITLE
seek help!  Traceback (most recent call last):   File "train_ssd.py", line 236, in <module>     target_transform=target_transform, is_test=True)   File "/home/z/MobileNetV3-SSD-master/vision/datasets/voc_dataset.py", line 17, in __init__     self.root = pathlib.Path(root)   File "/usr/lib/python3.6/pathlib.py", line 1001, in __new__     self = cls._from_parts(args, init=False)   File "/usr/lib/python3.6/pathlib.py", line 656, in _from_parts     drv, root, parts = self._parse_args(args)   File "/usr/lib/python3.6/pathlib.py", line 640, in _parse_args     a = os.fspath(a) TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by DENESTY** [shaoshengsong/MobileNetV3-SSD#26]

**Comment by DENESTY** [comment]
How to solve this
Traceback (most recent call last):
  File "train_ssd.py", line 236, in <module>
    target_transform=target_transform, is_test=True)
  File "/home/z/MobileNetV3-SSD-master/vision/datasets/voc_dataset.py", line 17, in __init__
    self.root = pathlib.Path(root)
  File "/usr/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by jideee** [comment]
Hello bro！ Have you solved the problem？ I meet this same question in SSD.
