### ISSUE TITLE
请问这个怎么改？

### ISSUE THREAD

**Issue by duanyuqi987** [shaoshengsong/MobileNetV3-SSD#6]
Traceback (most recent call last):
  File "run_ssd_live_demo.py", line 73, in <module>
    boxes, labels, probs = predictor.predict(image, 10, 0.4)
  File "/home/yajun/github/MobileNetV3-SSD/vision/ssd/predictor.py", line 37, in predict
    scores, boxes = self.net.forward(images)
  File "/home/yajun/github/MobileNetV3-SSD/vision/ssd/ssd.py", line 100, in forward
    locations, self.priors, self.config.center_variance, self.config.size_variance
  File "/home/yajun/github/MobileNetV3-SSD/vision/utils/box_utils.py", line 104, in convert_locations_to_boxes
    locations[..., :2] * center_variance * priors[..., 2:] + priors[..., :2],
RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float

**Comment by lingyi-learning** [comment]
同问

**Comment by shaoshengsong** [comment]
It is recommended that git clone this version
https://github.com/shaoshengsong/MobileNetV3-SSD-Compact-Version
